music_player/accounts/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('change-password/',views.MyPasswordChangeView.as_view(),name='reset'),
]

music_player/api/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns=[
    path('data',views.data,name='data'),
    path('song-update/<str:pk>/',views.songUpdate,name='song_update'),
]

music_player/music_player/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.startpage,name="startpage"),
    path('playlist/',include('playlist.urls')),
    path('accounts/',include('accounts.urls')),
    path('emotions/',include('emotions.urls')),
    path('api/',include('api.urls')),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music_player/accounts/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

from django.contrib.auth.forms import UserCreationForm
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django import forms


class UserCreateForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

        for field_name in ['username', 'password1', 'password2']:
            self.fields[field_name].help_text = None

music_player/accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from .models import UserCreateForm


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # login the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('startpage')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


@login_required(login_url='accounts:login')
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('startpage')


def signup_view(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('startpage')
    else:
        form = UserCreateForm()
    return render(request, 'accounts/signup.html', {'form': form})


class MyPasswordChangeView(PasswordChangeView):
    template_name = 'accounts/reset.html'
    success_url = reverse_lazy('startpage')

music_player/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="container">
    <div class="row mx-auto">
    
    <h1 align="center" class="text-white">Login</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {%csrf_token%}
        <p class="text-white">{{ form.as_p }}</p>
        {% if request.GET.next%}
        <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif%}
        <input type="submit" value="Login" class="btn btn-success">
    </form>
    </div>
  <div class="row mx-auto mt-5">

    
    <div class="not_user" >
        <h3>Not a User Yet, Click below to Sign Up</h3>
        <a href="{% url 'accounts:signup' %}" class="btn btn-primary">Sign Up</a>
    </div>
   </div>
</div>
{% endblock %}

music_player/accounts/templates/accounts/reset.html
{% extends 'base_layout.html' %}

{% block content %}
<form action="" method="post" class="mt-3">
    {%csrf_token%}
    <div >{{form.as_p}}</div>
    <button type="submit" class="btn btn-danger">Reset</button>
</form>
{%endblock%}

music_player/accounts/templates/accounts/signup.html
{% extends 'base_layout.html'%}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% block content %}
    <h1 style="padding-top: 50px;font-weight: bolder; padding-bottom: 20px; background-color: #ffcc66;" align="center">Signup</h1>
    <form style="display: inline-block; text-align: left;" class="site-form" action="/accounts/signup/" method="post" class="text-white">
        {%csrf_token%}
        <div>
            {{ form.as_p }}
        </div>
        {% if request.GET.next%}
        <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif%}
        <div align="center" class="button">
        <button type="submit" class="btn btn-primary">Signup</button>
        </div>
    </form>
{% endblock %}