music_player/api/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns=[
    path('data',views.data,name='data'),
    path('song-update/<str:pk>/',views.songUpdate,name='song_update'),
]

music_player/music_player/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.startpage,name="startpage"),
    path('playlist/',include('playlist.urls')),
    path('accounts/',include('accounts.urls')),
    path('emotions/',include('emotions.urls')),
    path('api/',include('api.urls')),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music_player/playlist/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name='playlist'

urlpatterns = [
        path('',views.general,name='general'),
        path('<int:type>/',views.emotion,name='emotion'),
        path('songupload/<int:type>/',views.song_upload,name='songupload'),
        path('up-song/',views.up_song,name='song'),
        path('fav/<int:id>',views.fav,name="fav"),
        path('delete/<int:type>/<int:id>/',views.delete,name='delete'),
        path('playsong/<int:sid>/',views.playsong,name='playsong'),
]

music_player/playlist/models.py
from django.contrib.auth.models import User
from django.db import models


class Song(models.Model):
    choices = ((0, 'happy'),
               (1, 'angry'),
               (2, 'sad'),
               (3, 'neutral'),
               (4, 'general'))

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    track = models.FileField(upload_to='Songs')
    type = models.IntegerField(choices)
    fav = models.BooleanField(default=False)
    name = models.CharField(max_length=30, default="Unknown", blank=True)

    def __str__(self):
        return self.name

music_player/playlist/forms.py
from django import forms
from .models import *


class SongUploadForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['track','name']

music_player/playlist/views.py
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Song
from .forms import *
from django.contrib import messages


# Create your views here.

@login_required(login_url='accounts:login')
def playsong(request, sid):
    user = request.user
    song = Song.objects.get(user=user, pk=sid)
    return render(request, "playlist/song.html", {"song":song})


@login_required(login_url='accounts:login')
def general(request):
    if request.method == 'POST':
        delSongs = request.POST.getlist('songoption')

        for songid in delSongs:
            song = Song.objects.get(pk=songid)
            song.delete()

        return redirect('playlist:general')
    emptyList = False
    user = request.user
    songs = Song.objects.all().filter(user=user)
    if len(songs) == 0:
        messages.info(request, f'Your playlist is empty.')
        emptyList = True

    return render(request, 'playlist/general.html', {'songs': songs, 'isEmpty': emptyList})


def emotion(request, type):
    user = request.user
    songs = Song.objects.all().filter(user=user, type=type)
    if len(songs) == 0:
        messages.info(request, f'Your playlist is empty.')
    dic = {0: 'Happy',
           1: 'Angry',
           2: 'Sad',
           3: 'Neutral'}
    return render(request, 'playlist/type.html', {'songs': songs, 'type': dic[type], 'emotion': type})


@login_required(login_url='accounts:login')
def song_upload(request, type):
    if request.method == "POST":
        form = SongUploadForm(request.POST, request.FILES)
        instance = form.save(commit=False)
        instance.user = request.user
        instance.type = type
        instance.save()
        return redirect('startpage')
    else:
        form = SongUploadForm()
    return render(request, 'playlist/song_upload.html', {'form': form, 'type': type})


@login_required(login_url='accounts:login')
def up_song(request):
    if request.method == "POST":
        form = SongUploadForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            typee = request.POST.get('playlist')
            instance.type = typee
            instance.save()
            return redirect('playlist:general')
    else:
        form = SongUploadForm()
    return render(request, 'playlist/up-song.html', {'form': form})


def fav(request, id):
    song = Song.objects.get(pk=id)
    temp = request.POST.get("fav")

    if temp == "yes":
        song.fav = True
        song.save()
    else:
        song.fav = False
        song.save()

    return JsonResponse(data={'fav': song.fav}, status=200)


@login_required(login_url='accounts:login')
def delete(request, type, id):
    song = Song.objects.get(pk=id)
    song.delete()
    if type == 4:
        return redirect('playlist:general')
    else:
        return redirect('playlist:emotion', type=type)

music_player/playlist/templates/playlist/general.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}
{% csrf_token %}
<a href="{% url 'playlist:song' %}" class="btn btn-primary mt-2" style="float:right;">Add New Song to your Playlists</a>
{% if not isEmpty %}
<div>
<button  id="delButton" class="btn btn-danger mr-5" style="float:right;margin-top: 9px;" onclick="delButtonOnClick()">Delete Multiple</button>
</div>
{% endif %}
{% if messages %}
{% for message in messages %}
<strong>{{message}}</strong>
{% endfor %}
{% endif %}
<h1 align="center"><u>Your Music</u></h1>
<form action="{% url 'playlist:general' %}" method="POST">
{% csrf_token %}

{% for song in songs %}
<!-- <div class="mt-4 card">
<div class="card-body" style="width: 18rem;">
<span style="font-size:37px;margin-bottom: 3px;">{{song.name}}</span>

    <audio controls  style="height:35px;background-color:black;color:black;" class="ml-3 mb-0">
        <source src="{{song.track.url}}" type="audio/mp3">
    </audio>

    <a href="{% url 'playlist:delete' type=4 id=song.id %}" class="btn btn-danger mr-5 delsolo" style="float:right;">Delete Song</a>

    <input type="checkbox" style="width:20px;height:20px;float:right;display:none;margin:2%" class="delMultiple" name="songoption" value="{{song.id}}">
-->





<div class="card mt-2 ml-4" style="width: 17rem;height: 20rem;float:left;">
    <img class="card-img-top" src="{% static 'download1.jpg' %}" alt="Card image cap">
    <h5 class="card-title">{{song.name}}</h5>
    <div>

    <!-- <audio controls  style="height:35px;background-color:black;color:black;">
        <source src="{{song.track.url}}" type="audio/mp3">
    </audio> -->
    <input type="checkbox" style="width:20px;height:20px;float:right;display:none;margin:2%" class="delMultiple" name="songoption" value="{{song.id}}">
    {% if song.fav %}
    <i id="fav{{song.id}}" class="fa fa-heart-o" style="color:red;cursor:pointer;margin-left:1%;font-size:30px" onclick="favchange(event,{{song.id}});"></i>
    {% else %}
    <i id="fav{{song.id}}" class="fa fa-heart-o" style="cursor:pointer;margin-left: 1%;font-size:30px;" onclick="favchange(event,{{song.id}});"></i>
    {% endif %}
    <a href="{% url 'playlist:playsong' sid=song.id %}" class="btn btn-primary ml-1 mb-1" style="font-size:15px;">Listen song</a>
    <a href="{% url 'playlist:delete' type=4 id=song.id %}" class="btn btn-danger delsolo ml-1 mb-1" >Delete Song</a>

    </div>
  </div>
{% endfor %}

<button type='submit' id="submitButton" class="btn btn-danger mr-5" style="display:none;float:right;" >Delete Selected</button>
</form>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>


    function delButtonOnClick(){

        elemnt=document.getElementById('delButton');
        elemnt.innerText="Delete Selected";
        elemnt.style.display="none";
        elemnt=document.getElementsByClassName('delsolo');
        for(var i=0;i<elemnt.length;i+=1){
            elemnt[i].style.display="none";
        }
        elemnt=document.getElementsByClassName('delMultiple');
        for(var i=0;i<elemnt.length;i+=1){
            elemnt[i].style.display="initial";
        }
        element=document.getElementById('submitButton');
        element.style.display="initial";

    }
    function favchange(event,id){
    var csrf=$("input[name=csrfmiddlewaretoken]").val();
    var elemnt=document.getElementById("fav"+id);

    if (elemnt.style.color=='red'){
        $.ajax({
            url:'/playlist/fav/' + id,
            data:{
                csrfmiddlewaretoken : csrf,
                fav : "no"
            },
            type:'post',
            success : function(response){
                elemnt.style.color='black';
            }


        });




    }
    else{
        $.ajax({
            url:'/playlist/fav/' + id,
            data:{
                csrfmiddlewaretoken : csrf,
                fav : "yes"
            },
            type:'post',
            success : function(response){
                elemnt.style.color='red';
            }


        });

    }
    }



</script>






{% endblock %}

music_player/playlist/templates/playlist/song_upload.html
{% extends 'base_layout.html' %}
{% block content %}
    <form action="{% url 'playlist:songupload' type %}" method="post" enctype="multipart/form-data" class="mt-3">
        {%csrf_token%}
        <div class="song_upload">{{ form.as_p }}</div>
        <button type="submit" class="btn btn-primary" >Continue</button>
    </form>
{% endblock %}

music_player/playlist/templates/playlist/type.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}
    <a href="{% url 'playlist:songupload' emotion %}" class="btn btn-primary mt-2" style="float:right;">Add Song</a>
    <h3 align="center" class="text-info"><u>Your {{type}} Playlist</u></h3>
    {% if messages %}
        {% for message in messages %}
        <ul class="text-warning"><strong>{{message}}</strong></ul>
        {% endfor %}
    {% endif %}
    <div style="margin:2%;">
    
    <button type="button"  style="float:right;margin-right: 1%;" class="btn btn-dark feedback" value="No" onclick="feedbackHandle(event)">No</button>
    <button type="button"  style="float:right;margin-right: 1%;" class="btn btn-success feedback" value="Yes" onclick="feedbackHandle(event)">Yes</button>
    <!-- <input style="float:right;margin-right: 1%;" class="btn btn-dark feedback" type="button" value="No">
    <input style="float:right;margin-right: 1%;" class="btn btn-success feedback" type="button" value="Yes"> -->
    
    <strong style="float:right;margin-right: 1%;" class="feedback">Was the prediction right?</strong>
    <span id="err" style="display:none;float:right;height:2.5em;margin-right: 2%;" class="alert alert-info" role="alert"></span>
    </div>
<br>
<hr>


{% for song in songs %}
<div class="card mt-2 ml-4" style="width: 17rem;height: 20rem;float:left;">
    <img class="card-img-top" src="{% static 'download1.jpg' %}" alt="Card image cap">
    <h5 class="card-title">{{song.name}}</h5>
    <div>
    <input type="checkbox" style="width:20px;height:20px;float:right;display:none;margin:2%" class="delMultiple" name="songoption" value="{{song.id}}">
    {% if song.fav %}
    <i id="fav{{song.id}}" class="fa fa-heart-o" style="color:red;cursor:pointer;margin-left:1%;font-size:30px" onclick="favchange(event,{{song.id}});"></i>
    {% else %}
    <i id="fav{{song.id}}" class="fa fa-heart-o" style="cursor:pointer;margin-left: 1%;font-size:30px;" onclick="favchange(event,{{song.id}});"></i>
    {% endif %}
    <a href="{% url 'playlist:playsong' sid=song.id %}" class="btn btn-primary ml-1 mb-1" style="font-size:15px;">Listen song</a>
    <a href="{% url 'playlist:delete' type=4 id=song.id %}" class="btn btn-danger delsolo ml-1 mb-1" >Delete Song</a>
    </div>
</div>
{% endfor %}

<script>
    function feedbackHandle(event){
        var feedback=event.target.value;
        elements=document.getElementsByClassName("feedback");
        
        for(var i=0;i<elements.length;i+=1){
            elements[i].style.display="none";
            
        }
    
        element=document.getElementById("err");
        
        if (feedback=="Yes"){
            element.innerText="Thanks for the feedback";
            element.style.display="initial";
        
        }
        else{
            element.innerText="Will serve you better next time";
            element.style.display="initial"; 
        }

    }
</script>

{% endblock %}

music_player/playlist/templates/playlist/up-song.html
{% extends 'base_layout.html' %}
{% block content %}
    <form action="{% url 'playlist:song' %}" method="post" enctype="multipart/form-data" class="mt-3" method="post">
        {%csrf_token%}
        <div class="song">
            <label for="playlist">Choose Playlist:</label>
            <select name="playlist">
                <option value="0">Happy</option>
                <option value="1">Angry</option>
                <option value="2">Sad</option>
                <option value="3">Neutral</option>
                <option value="4">General</option>
            </select>
            <p></p>
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary" >Continue</button>
    </form>
{% endblock %}