music_player/accounts/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('change-password/',views.MyPasswordChangeView.as_view(),name='reset'),
]

music_player/api/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns=[
    path('data',views.data,name='data'),
    path('song-update/<str:pk>/',views.songUpdate,name='song_update'),
]

music_player/emotions/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='emotions'

urlpatterns=[
    path("prediction/",views.predict,name="prediction"),
    ]

music_player/music_player/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.startpage,name="startpage"),
    path('playlist/',include('playlist.urls')),
    path('accounts/',include('accounts.urls')),
    path('emotions/',include('emotions.urls')),
    path('api/',include('api.urls')),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music_player/playlist/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name='playlist'

urlpatterns = [
        path('',views.general,name='general'),
        path('<int:type>/',views.emotion,name='emotion'),
        path('songupload/<int:type>/',views.song_upload,name='songupload'),
        path('up-song/',views.up_song,name='song'),
        path('fav/<int:id>',views.fav,name="fav"),
        path('delete/<int:type>/<int:id>/',views.delete,name='delete'),
        path('playsong/<int:sid>/',views.playsong,name='playsong'),
]

music_player/templates/base_layout.html
{% load static %}

<html lang="en">
<head>
{% block head %}
{% endblock %}
<style>
 body {
  margin: 0;
  padding: 0;
  width:100vw;
  height: 100vh;
  background-color: #eee;
}
.content {
  display: flex;
  justify-content: center;
  align-items: center;
  width:100%;
  height:100%;
}
.loader-wrapper {
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
  background-color: #242f3f;
  display:flex;
  justify-content: center;
  align-items: center;
}
.loader {
  display: inline-block;
  width: 30px;
  height: 30px;
  position: relative;
  border: 4px solid #Fff;
  animation: loader 2s infinite ease;
}
.loader-inner {
  vertical-align: top;
  display: inline-block;
  width: 100%;
  background-color: #fff;
  animation: loader-inner 2s infinite ease-in;
}
@keyframes loader {
  0% { transform: rotate(0deg);}
  25% { transform: rotate(180deg);}
  50% { transform: rotate(180deg);}
  75% { transform: rotate(360deg);}
  100% { transform: rotate(360deg);}
}
@keyframes loader-inner {
  0% { height: 0%;}
  25% { height: 0%;}
  50% { height: 100%;}
  75% { height: 100%;}
  100% { height: 0%;}
}
</style>

    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href = "{%static 'style.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Beyond Music</title>
</head>
<body>
  <div class="loader-wrapper">
      <span class="loader"><span class="loader-inner"></span></span>
  </div>
    <header>
        <div class="logo">
            <a href="{% url 'startpage' %}"><img class="logoo" src="{% static 'logo.jpg' %}"></a>
            {% if user.is_authenticated%}
            <form class="logout-link mt-5 mr-2" action="{%url 'accounts:logout'%}" method="post" style="float:right;">
                {%csrf_token%}
                <input type="submit" value="Logout" class="btn btn-warning mt-10">
            </form>
            <a href="{%url 'accounts:reset'%}" class="btn btn-danger mt-5 mr-2" style="float:right;"> Reset Password</a>
            {% else %}
            <a class="btn btn-success mt-5 mr-3" href="{% url 'accounts:login' %}" style="float:right;">Login</a>
            {% endif %}

            {% if "/" == request.path %}
            <a href="{% url 'startpage' %}" class="btn btn-info mt-5 mr-2" style="float:right; display:none;">Home Page</a>
            {% elif "/accounts/login/" == request.path %}
            <a href="{% url 'startpage' %}" class="btn btn-info mt-5 mr-2" style="float:right; display:none;">Home Page</a>
            {% else %}
            <a href="{% url 'startpage' %}" class="btn btn-info mt-5 mr-2" style="float:right; display:block;">Home Page</a>
            {% endif %}
        </div>
        <div class="wrapper mt-0 ml-3">
            {% block content %}
            {% endblock %}
        </div>
    </header>



    <script>
        $( document ).ready(function() {
            $(".loader-wrapper").fadeOut("slow");
        });
    </script>




</body>
</html>

music_player/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h1>Homepage</h1>

</body>
</html>

music_player/templates/start.html
{% extends 'base_layout.html' %}
{% block content %}
    <h3>Welcome To Emotion Based Music Player</h3>
    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <strong>{{message}}</strong>
    {% endfor %}
    </ul>
    {% endif %}
    <form action="{% url 'emotions:prediction' %}" method="POST" enctype='multipart/form-data'>
        {% csrf_token %}
        <div class="prediction">
            {{ form.as_p }}
        </div>
        <button class="btn btn-primary">Continue</button>
    </form>
        {% if request.GET.next%}
        <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
    <br>
    <br>
    <br>
    <h6>OR</h6>
    <a href="{% url 'playlist:general' %}"><h2>Go for default music player</h2></a>
{% endblock %}